lesson_11_project/calc/urls.py
from django.contrib import admin
from django.urls import path
from calc.views import Index, Result

app_name = 'calc'
urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('result/', Result.as_view(), name='result'),
]

lesson_11_project/lesson_11/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('calc/', include('calc.urls')),
]

lesson_11_project/calc/models.py
from django.db import models
import datetime

__all__ = {'Operation'}


class Operation(models.Model):
    operand_1: str = models.CharField(max_length=30, null=False, blank=False, help_text='Operand_1',
                                      verbose_name='Operand_1')
    operator: str = models.CharField(max_length=2, null=False, blank=False, help_text='Operator',
                                     verbose_name='Operator')
    operand_2: str = models.CharField(max_length=30, null=False, blank=False, help_text='Operand_2',
                                      verbose_name='Operand_2')
    result_operation: str = models.CharField(max_length=50, null=False, blank=False, help_text='Result_operation',
                                             verbose_name='Result_operation')
    date_operation: datetime.datetime = models.DateTimeField(help_text='Date operation', verbose_name='Date operation',
                                                             auto_now_add=True)

    def __str__(self) -> str:
        return f'{__class__.__name__} ({self.operand_1}{self.operator}{self.operand_2}={self.result_operation})'

lesson_11_project/calc/views.py
from django.contrib import messages
from django.shortcuts import render
from django.views import View

from calc.models import Operation


class Index(View):
    def get(self, request):
        return render(request, 'calc/index.html')


class Result(View):
    def _calculate(self, operand_1, operator, operand_2):
        result = None
        if operator == '+':
            result = operand_1 + operand_2
        elif operator == '-':
            result = operand_1 - operand_2
        elif operator == '*':
            result = operand_1 * operand_2
        elif operator == '/':
            try:
                result = operand_1 / operand_2
            except ZeroDivisionError:
                result = 'ZeroDivisionError'
        elif operator == '**':
            result = operand_1 ** operand_2
        return result

    def post(self, request):
        operand_1 = request.POST['input_1']
        operator = request.POST['list_operators']
        operand_2 = request.POST['input_2']
        result_operation = self._calculate(int(operand_1), operator, int(operand_2))
        if result_operation == 'ZeroDivisionError':
            messages.error(request, 'Error: division by zero!')
            return render(request, 'calc/index.html')
        new_operation_object = Operation(operand_1=operand_1, operator=operator, operand_2=operand_2,
                                         result_operation=result_operation)
        new_operation_object.save()

        last_10_operation = Operation.objects.order_by('-id')[:10]
        return render(request, 'calc/result.html', context=dict(last_10_operation=last_10_operation))

lesson_11_project/calc/templates/calc/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>
<form action="{% url 'calc:result' %}" method="post">
    {% csrf_token %}
    <input type="text" name="input_1">
    <select name="list_operators">
        <option value="+">+</option>
        <option value="-">-</option>
        <option value="*">*</option>
        <option value="/">/</option>
        <option value="**">**</option>
    </select>
    <input type="text" name="input_2">
    <input type="submit" value="Send">
</form>
{% if messages %}
    {% for message in messages %}
        <p>{{ message }}</p>
    {% endfor %}
{% endif %}
</body>
</html>

lesson_11_project/calc/templates/calc/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Result</title>
</head>
<body>
<p>Last 10 operation:</p>
{% for operation in last_10_operation %}
    <p><b>{{ forloop.counter }}.</b> {{ operation.operand_1 }} {{ operation.operator }} {{ operation.operand_2 }}
        = {{ operation.result_operation }} | {{ operation.date_operation }}</p>
{% endfor %}
<br>
<a href="{% url 'calc:index' %}">На главную страницу</a>
</body>
</html>