lesson_11_2_project/home/urls.py
from django.urls import path

from home.views import HomePage

app_name = 'home'
urlpatterns = [
    path('', HomePage.as_view(), name='index'),
]

lesson_11_2_project/lesson_11_2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('registration/', include('registration.urls')),
    path('stats/', include('stats.urls')),
    path('admin/', admin.site.urls),
]

lesson_11_2_project/registration/urls.py
from django.contrib import admin
from django.urls import path, include

from registration.views import Registration, Result

app_name = 'registration'
urlpatterns = [
    path('', Registration.as_view(), name='registration'),
    path('result/', Result.as_view(), name='result'),
]

lesson_11_2_project/stats/urls.py
from django.urls import path

from stats.views import Stats

app_name = 'stats'
urlpatterns = [
    path('', Stats.as_view(), name='stats'),
]

lesson_11_2_project/home/models.py
from django.db import models

# Create your models here.

lesson_11_2_project/stats/models.py
from django.db import models

# Create your models here.

lesson_11_2_project/home/views.py
from django.shortcuts import render
from django.views import View

from registration.models import Check

__all__ = {'HomePage'}


class HomePage(View):
    def get(self, request):
        all_products = Check.objects.order_by('-id')[:5]
        return render(request, 'home/index.html', dict(products=all_products))

lesson_11_2_project/stats/views.py
from datetime import datetime

from django.shortcuts import render
from django.views import View

from registration.models import Check

__all__ = {'Stats'}


class Stats(View):
    def get(self, request):
        most_expensive_product_today = Check.objects.filter(date_create_check__gte=datetime.now().date()).order_by(
            'cost_product').last()
        cheapest_product_today = Check.objects.filter(date_create_check__gte=datetime.now().date()).order_by(
            '-cost_product').last()
        return render(request, 'stats/stats.html', dict(most_expensive_product_today=most_expensive_product_today,
                                                        cheapest_product_today=cheapest_product_today))

lesson_11_2_project/home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Сost Сontrol - Home Page</title>
</head>
<body>
<h1>Сost Сontrol - Home Page</h1>
<table width="50%" border="1" cellspacing="0" cellpadding="4">
    <caption><h2>5 Last Receipt:</h2></caption>
    <tr>
        <th>Product</th>
        <th>Cost</th>
        <th>Date</th>
    </tr>
    {% for product in products %}
        <tr>
            <td>{{ product.product_name }}</td>
            <td>{{ product.cost_product }}</td>
            <td>{{ product.date_create_check }}</td>
        </tr>
    {% endfor %}
</table>
<br>
<a href="{% url 'registration:registration' %}">Add Receipt</a>
<br>
<a href="{% url 'stats:stats' %}">View statistics</a>
</body>
</html>

lesson_11_2_project/stats/templates/stats/stats.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Сost Сontrol - Stats</title>
</head>
<body>
<h1>Сost Сontrol - Stats</h1>

<table width="50%" border="1" cellspacing="0" cellpadding="4">
    <caption><h2>The most expensive product today:</h2></caption>
    <tr>
        <th>Product</th>
        <th>Cost</th>
        <th>Cost</th>
    </tr>
    <tr>
        <td>{{ most_expensive_product_today.product_name }}</td>
        <td>{{ most_expensive_product_today.cost_product }}</td>
        <td>{{ most_expensive_product_today.date_create_check }}</td>
    </tr>
</table>

<table width="50%" border="1" cellspacing="0" cellpadding="4">
    <caption><h2>The cheapest product today:</h2></caption>
    <tr>
        <th>Product</th>
        <th>Cost</th>
        <th>Cost</th>
    </tr>
    <tr>
        <td>{{ cheapest_product_today.product_name }}</td>
        <td>{{ cheapest_product_today.cost_product }}</td>
        <td>{{ cheapest_product_today.date_create_check }}</td>
    </tr>
</table>
<br>
<a href="{% url 'home:index' %}">Return to Home Page</a>
</body>
</html>